corrected (dead-)links
Z-Hub/Z-Push pull request #37
Opened 2023-11-26 09:12 UTC by PhilPhonic

What does this implement/fix? Explain your changes.
---------------------------------------------------
updated (dead-)links

Does this close any currently open issues?
------------------------------------------
no

Any relevant logs, error output, etc?
-------------------------------------
n/a

Where has this been tested?
---------------------------
**Server (please complete the following information):**
 - OS: debian 11.8
 - PHP Version: 7.4

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Mail App [e.g. GMail, Apple Mail] 
 - Version [e.g. 22]

2023-11-26 09:58 UTC, fbartels commented on src/lib/core/zpush.php
> +        <a href="https://z-push.org/">Z-Push homepage</a><br>
The current redirect does not seem to allow this. for me this throws a 403.

2024-01-08 02:06 UTC, matidau requested changes

2024-01-08 02:06 UTC, matidau commented on src/lib/core/zpush.php
> -        <a href="http://z-push.org/download">Z-Push download page</a><br>
@PhilPhonic We (thanks to @fbartels) now have z-push.org working against the github pages site.
Can you revert this change to `https://z-push.org/download` or `https://z-push.org/download/`

2024-01-08 02:06 UTC, matidau commented on src/lib/core/zpush.php
> -        <a href="http://z-push.org/download">Z-Push download page</a><br>
sorry http or https is fine 🙂

2024-04-28 12:37 UTC, merged

2024-04-29 09:27 UTC, matidau commented
Thanks for this 😊